import clpFfiJsModuleInit from "clp-ffi-js/node";
import {readFile, unlink, writeFile} from "fs/promises"
import {resolve} from "path"
import {describe, expect, it} from "vitest";

import {DALEngine} from "../../src/DALEngine.js";

/**
 * Loads the trace logs from the given trace raw data.
 * @param {Object} traceRaw The raw trace data to load the logs from.
 * @returns {Promise<Array>} Promise that resolves to an array of LogEntry
 * @param traceRaw
 */
async function loadTrace (traceRaw) {
    const Module = await clpFfiJsModuleInit();
    const decoder = new Module.ClpStreamReader(traceRaw, {
        timestampKey: {isAutoGenerated: true, parts: ["timestamp", "unix_millisecs"]},
        logLevelKey: {isAutoGenerated: true, parts: ["level", "name"]}}
    );
    const logs = decoder.decodeRange(0, decoder.deserializeStream(), false);
    return logs;
}

describe("debugger tests", () => {

    it("debugs an execution trace for library manager", async () => {
        const d = new DALEngine({
            name: "Execution Trace Walker",
            description: "Walks through execution traces",
        });

        const filePath = resolve(__dirname, "../test_data/demo2.dal");
        const source = await readFile(filePath);

        d.deserialize(source);

        const traceIds = d.traces._traces;

        const traceWithViolations = traceIds[1];

        const traceLogs = await loadTrace(traceWithViolations.trace);

        const debuggerInstance = d.createDebugger(traceLogs);
        debuggerInstance.run();

        const filePath2 = resolve(__dirname, "../temp/demo2_debugger_output.txt");
        await writeFile(
            filePath2, JSON.stringify(
                debuggerInstance._executableSemanticModelOutputs, null, 2
            )
        );
    });
});
