import clpFfiJsModuleInit from "clp-ffi-js/node";
import {readFile, unlink, writeFile} from "fs/promises"
import {resolve} from "path"
import {describe, expect, it} from "vitest";

import {DALEngine} from "../../src/DALEngine.js";

/**
 * Loads the trace logs from the given trace raw data.
 * @param {Object} traceRaw The raw trace data to load the logs from.
 * @returns {Promise<Array>} Promise that resolves to an array of LogEntry
 * @param traceRaw
 */
async function loadTrace (traceRaw) {
    const Module = await clpFfiJsModuleInit();
    const decoder = new Module.ClpStreamReader(traceRaw.trace, {
        timestampKey: {isAutoGenerated: true, parts: ["timestamp", "unix_millisecs"]},
        logLevelKey: {isAutoGenerated: true, parts: ["level", "name"]}}
    );
    const logs = decoder.decodeRange(0, decoder.deserializeStream(), false);
    return logs;
}

describe("debugger tests", () => {

    it("debugs an execution trace", async () => {
        const d = new DALEngine({
            name: "Library Manager",
            description: "Manages the library",
        });

        const filePath = resolve(__dirname, "../test_data/library_manager.dal");
        const source = await readFile(filePath);

        d.deserialize(source);

        const traceIds = Object.keys(d.implementation._traces);

        const traceNoViolations = traceIds[0]; // Trace with no violations
        const traceWithViolation = traceIds[1]; // Trace with min length violation

        const traceLogs = await loadTrace(d.implementation.getTrace(traceWithViolation));

        const debuggerInstance = d.createDebugger(traceWithViolation, traceLogs);
        debuggerInstance.run();

        const filePath2 = resolve(__dirname, "../temp/transitions.txt");
        await writeFile(
            filePath2, JSON.stringify(debuggerInstance._atomicPathsLog, null, 2)
        );
    });
});
