class LogEntry {
    constructor (log) {
        this._log = log;
        this._logMessage = JSON.parse(log.message);
        this.autoGenerated = this._logMessage["auto-generated"];
        this.userGenerated = this._logMessage["user-generated"];
    }

    getType () {
        return this.userGenerated.type;
    }

    getTimestamp () {
        return this.autoGenerated.timestamp.unix_millisecs;
    }

    getBehavior () {
        return this.userGenerated.behaviorName;
    }
};

export default LogEntry;
