class LogEntry {
    constructor (log) {
        this._log = log;
        // TODO: This is because of JSON serialization, will deal
        // with this later as well.
        this._log.timestamp = Number(this._log.timestamp);
        this._logMessage = JSON.parse(log.message);
        this.autoGenerated = this._logMessage["auto-generated"];
        this.userGenerated = this._logMessage["user-generated"];
    }

    getType () {
        return this.userGenerated.type;
    }

    getTimestamp () {
        return this.autoGenerated.timestamp.unix_millisecs;
    }

    getBehavior () {
        return this.userGenerated.behaviorName;
    }

    getParticipantName () {
        return this.userGenerated.participantName;
    }

    getParticipantValue () {
        return this.userGenerated.participantValue;
    }
};

export default LogEntry;
