// NOTE: This is temporary, I will export separate builds for node
// and browser, so that I won't need to do this dynamic import.
let clpFfiJsModuleInit;
if (typeof window === "undefined") {
    clpFfiJsModuleInit = await import("clp-ffi-js/node");
} else {
    clpFfiJsModuleInit = await import("clp-ffi-js");
}

class TraceDebugger {
    /**
     * Initializes a trace debugger that accepts the design and the trace. The
     * design serves as an authoritative semantic model that is used to
     * determine the correctness of the traces behavior and automatically
     * debug it. The result of a debugger being unable to debug a trace is
     * an input into the design that results it in learning new semantics.
     *
     * In this sense, this debugger is a tool for the design to learn new
     * semantics by being exposed to new traces that it cannot explain.
     * It also serves as the authoritative model for testing the traces
     * produced by implementations of the design, meaning, it can be used
     * to verify that the traces produced by implementations are semantically
     * valid and respect the invariants of the design.
     *
     * @param {Object} design The design to use as the authoritative semantic
     * model for debugging.
     * @param {Object} implementation The implementation to use for debugging.
     * @param {String} traceId The ID of the trace to debug.
     */
    constructor (design, implementation, traceId) {
        this._implementation = implementation;
        this._traceId = traceId;
        this._design = design;
    }

    /**
     * Load the trace file and 
     */
    async loadTrace () {
        const traceRaw = this._implementation.getTrace(this._traceId);

        const Module = await clpFfiJsModuleInit.default();
        // TODO: When serializing, I'm using JSON.stringify which is causing
        // the uintarray (trace) to be converted to an object with numeric keys.
        // I'm using Object.values to get the values of the object and
        // convert it back to a Uint8Array. I will fix this,
        const decoder = new Module.ClpStreamReader(Uint8Array.from(Object.values(traceRaw.trace)), {
            timestampKey: {isAutoGenerated: true, parts: ["timestamp", "unix_millisecs"]},
            logLevelKey: {isAutoGenerated: true, parts: ["level", "name"]}}
        );
        const logs = decoder.decodeRange(0, decoder.deserializeStream(), false);

        for (const log of logs) {
            const msg = JSON.parse(log.message);
            const loggedMsg = msg["user-generated"];

            if (loggedMsg["type"] === "variable") {
                console.log(loggedMsg);
            }
        }

    }
}

export default TraceDebugger;
