export default class File {
    /**
     * The file object represents a source file in the implementation. It is
     * represented by a path and contains multiple versions of the source file.
     * Each version is generated by a save operation and it is represented by
     * the source object.
     *
     * Note: Currently, this file does not track version information, I am
     * simply saving a source.
     *
     * Note2: There is another layer of version abstraction where files that
     * are renamed or moved need to be tracked. I am also not implementing this
     * right now but it is clear how that will work and it will be added after
     * other functionality is added.
     *
     * @param {String} path Path of the source file.
     */
    constructor (path) {
        this._versions = [];
        this._path = path;
    }

    /**
     * Adds a source version to the file.
     * @param {Source} source Source object
     */
    addVersion (source) {
        this._versions.push(source);
    }

    /**
     * Gets the source version given a version ID.
     * @param {String} versionId Version ID of the source version to get.
     * @returns {Source} The source version with the given version ID.
     * @throws {Error} Throws an error if a source version with the given
     * version ID does not exist in the file.
     */
    getVersion (versionId) {
        const version = this._versions.find(version => version.getVersionId() === versionId);
        if (!version) {
            throw new Error(`Source version with ID ${versionId} does not exist in the file.`);
        }
        return version;
    }

    /**
     * Gets all source versions in the file.
     * @returns {Array} List of source versions in the file.
     */
    getVersions () {
        return this._versions;
    }

    /**
     * Returns the latest source version in the file.
     * @returns {Source} Source object representing version of source file.
     */
    getLatestVersion () {
        if (this._versions.length === 0) {
            throw new Error("No source versions exist in the file.");
        }
        return this._versions[this._versions.length - 1];
    }

    /**
     * Returns the path of this file.
     * @returns {String} Path of this file.
     */
    getPath () {
        return this._path;
    }

    /**
     * For the latest version of the source file, set the behavior ID for
     * the statement with the given statement ID.
     * @param {String} stmtId ID of the mapped statement.
     * @param {String} behaviorId ID of the behavior.
     */
    setBehaviorId (stmtId, behaviorId) {

    }

    /**
     * Given a statment ID, return the behavior assigned to the mapped stmt.
     * @param {String} stmtId ID of the mapped statement.
     * @returns {String} ID of the behavior assigned to the mapped statement.
     */
    getBehaviorId (stmtId) {

    }
};
