import Source from "./Source";

export default class File {
    /**
     * The file object represents a source file in the implementation. It is
     * represented by a path and contains multiple versions of the source file.
     * Each version is generated by a save operation and it is represented by
     * the source object.
     *
     * I am setting up this class with the high level functions needed to 
     * support mapping statements in a source file to the design. This means
     * that in the workbench, when the user clicks on a statement, this file
     * API will be used to:
     * -  set or remove the behavior from the statement.
     * -  add participants and variable names to a statement.
     *
     * When the user wants to instrument the source file, this API will export
     * provide a method to get the source and mapping in a format that the
     * instrumenter can use. The implementation API will be a higher level
     * abstraction that will provide the output of this file API while
     * preserving the directory structure needed by the instrumenting tool.
     *
     * Note: Currently, this file does not track version information, I am
     * simply saving a source in a single version. Versioning will be added
     * after but this sets up the structure needed to implement that.
     *
     * Note2: There is another layer of version abstraction where files that
     * are renamed or moved need to be tracked. I am also not implementing this
     * right now but it is clear how that will work and it will be added after
     * other functionality is added.
     *
     * @param {String} path Path of the source file.
     */
    constructor (path) {
        this._versions = [];
        this._path = path;
        this._activeVersion = null;
    }

    /**
     * Adds a source version to the file.
     */
    addVersion () {
        const source = new Source({uid: `source${this._versions.length + 1}`});
        // TODO: This will be extended as versioning is develope further.
        source.setVersionId(`version${this._versions.length + 1}`);
        this._activeVersion = source;
        this._versions.push(source);
    }

    /**
     * Gets the source version given a version ID.
     * @param {String} versionId Version ID of the source version to get.
     * @returns {Source} The source version with the given version ID.
     * @throws {Error} Throws an error if a source version with the given
     * version ID does not exist in the file.
     */
    getVersion (versionId) {
        const version = this._versions.find(version => version.getVersionId() === versionId);
        if (!version) {
            throw new Error(`Source version with ID ${versionId} does not exist in the file.`);
        }
        return version;
    }

    /**
     * Gets all source versions in the file.
     * @returns {Array} List of source versions in the file.
     */
    getVersions () {
        return this._versions;
    }

    /**
     * Returns the latest source version in the file.
     * @returns {Source} Source object representing version of source file.
     */
    getLatestVersion () {
        // TODO: Modify to use creation time instead of array order.
        if (this._versions.length === 0) {
            throw new Error("No source versions exist in the file.");
        }
        return this._versions[this._versions.length - 1];
    }

    /**
     * Returns the path of this file.
     * @returns {String} Path of this file.
     */
    getPath () {
        return this._path;
    }

    /**
     * Sets the content of the latest version of the source file.
     * @param {String} content Content of the source file.
     */
    addContent (content) {
        const latestVersion = this.getLatestVersion();
        latestVersion.setContent(content);
    }

    /**
     * Adds a statement index to the latest version of the source file.
     * @param {JSON} statementIndex Mapping of statements to source file.
     */
    addStatementIndex (statementIndex) {
        const latestVersion = this.getLatestVersion();
        latestVersion.addStatementIndex(statementIndex);
    }

    /**
     * For the latest version of the source file, set the behavior ID for
     * the statement with the given statement ID.
     * @param {String} stmtId ID of the mapped statement.
     * @param {String} behaviorId ID of the behavior.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    setBehaviorId (stmtId, behaviorId) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementIndexEntryByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        stmtIndexEntry.setBehavior(behaviorId);
    }

    /**
     * Clears the behavior ID for the statement with the given stmtId in
     * the latest version of the source file.
     * @param {String} stmtId StmtId of the mapped statement.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    clearBehaviorId (stmtId) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementIndexEntryByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        stmtIndexEntry.setBehaviorId(null);
        // TODO: Clear the participants and variables.
    }

    /**
     * Given a statment ID, return the behavior assigned to the mapped stmt.
     * @param {String} stmtId ID of the mapped statement.
     * @returns {String} ID of the behavior assigned to the mapped statement.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    getMappedStatement (stmtId) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementIndexEntryByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        return stmtIndexEntry;
    }
};
