import {DalAstGenerator} from "dal-ast-js";

import Base from "../Base";
import MissingAttributes from "../Errors/MissingAttributes";
import isLoadedFromFile from "../helpers/isLoadedFromFile";
import Source from "./Source";

export default class File extends Base {
    /**
     * The file object represents a source file in the implementation. It is
     * represented by a path and contains multiple versions of the source file.
     * Each version is generated by a save operation and it is represented by
     * the source object.
     *
     * I am setting up this class with the high level functions needed to
     * support mapping statements in a source file to the design. This means
     * that in the workbench, when the user clicks on a statement, this file
     * API will be used to:
     * -  set or remove the behavior from the statement.
     * -  add participants and variable names to a statement.
     *
     * When the user wants to instrument the source file, this API will
     * provide a method to get the source and mapping in a format that the
     * instrumenter can use. The implementation API will be a higher level
     * abstraction that will provide the output of this file API while
     * preserving the directory structure needed by the instrumenting tool.
     *
     * Note: Currently, this file does not track version information, I am
     * simply saving a source in a single version. Versioning will be added
     * after but this sets up the structure needed to implement that.
     *
     * Note2: There is another layer of version abstraction where files that
     * are renamed or moved need to be tracked. I am also not implementing this
     * right now but it is clear how that will work and it will be added after
     * other functionality is added.
     *
     * @param {String} name Name of the source file.
     * @param {String} key Path of the source file.
     * @param args
     */
    constructor (args) {
        super();
        this._name = args.name;
        this._versions = [];
        this._key = args.key;
        this._activeVersion = null;
        this._uid = crypto.randomUUID();
        this._ast = null;
        (isLoadedFromFile(args) ? this._loadFromFile(args) : this._loadArgs(args));
    }

    /**
     * Loads the provided arguments.
     *
     * @throws {MissingAttributes} Thrown when required attr is not present.
     * @param {Object} args
     */
    _loadArgs (args) {
        const expectedAttributes = ["name", "key"];
        if (typeof args !== "object" || args === null || Array.isArray(args)) {
            // Not an object, so all attributes are missing.
            throw new MissingAttributes("File", expectedAttributes);
        }
        expectedAttributes.forEach((attr) => {
            if (!(attr in args)) {
                throw new MissingAttributes("File", attr);
            }
            this["_" + attr] = args[attr];
        });
    }

    _loadFromFile (savedJSON) {
        for (const [key, value] of Object.entries(savedJSON)) {
            if (key === "_versions") {
                value.forEach(node => this._versions.push(new Source(node)));

                // Load the active version if it was saved by finding
                // it in the versions array.
                if (savedJSON._activeVersion?._versionId) {
                    this._activeVersion = this._versions.find(
                        version => version.getVersionId() === savedJSON._activeVersion._versionId
                    );
                }

            } else if (key !== "_activeVersion") {
                // We skip active version, because we are manually finding it
                // in the versions array and setting it.
                this[key] = savedJSON[key];
            }
        };
    }

    /**
     * Get the ast for the given behavioral script.
     * @returns {Object} AST of the script.
     */
    generateAst () {
        if (!this._name.endsWith(".dal")) {
            throw new Error("File is not a design.")
        }
        const source = this._activeVersion.getContent();
        this._ast = new DalAstGenerator().run(source);
        return this._ast;
    }

    /**
     * Returns the generated AST.
     * @returns {Object} Generated AST.
     */
    getAst () {
        return this._ast;
    }

    /**
     * Returns the name of the file.
     * @returns {String} Name of the file.
     */
    getName () {
        return this._name;
    }

    /**
     * Returns the UID of the file.
     * @returns {String} UID of the file.
     */
    getUid () {
        return this._uid;
    }

    /**
     * Adds a source version to the file.
     */
    addVersion () {
        const source = new Source({uid: `source${this._versions.length + 1}`});
        // TODO: This will be extended as versioning is develope further.
        source.setVersionId(`version${this._versions.length + 1}`);
        this._activeVersion = source;
        this._versions.push(source);
    }

    /**
     * Gets the source version given a version ID.
     * @param {String} versionId Version ID of the source version to get.
     * @returns {Source} The source version with the given version ID.
     * @throws {Error} Throws an error if a source version with the given
     * version ID does not exist in the file.
     */
    getVersion (versionId) {
        const version = this._versions.find(version => version.getVersionId() === versionId);
        if (!version) {
            throw new Error(`Source version with ID ${versionId} does not exist in the file.`);
        }
        return version;
    }

    /**
     * Gets all source versions in the file.
     * @returns {Array} List of source versions in the file.
     */
    getVersions () {
        return this._versions;
    }

    /**
     * Returns the latest source version in the file.
     * @returns {Source} Source object representing version of source file.
     */
    getLatestVersion () {
        // TODO: Modify to use creation time instead of array order.
        if (this._versions.length === 0) {
            throw new Error("No source versions exist in the file.");
        }
        return this._versions[this._versions.length - 1];
    }

    /**
     * Returns the path of this file.
     * @returns {String} Path of this file.
     */
    getKey () {
        return this._key;
    }

    /**
     * Sets the content of the latest version of the source file.
     * @param {String} content Content of the source file.
     */
    setContent (content) {
        this._activeVersion.setContent(content);
    }

    /**
     * Returns the content of the source file.
     * @returns {String} Content of file.
     */
    getContent () {
        return this._activeVersion.getContent();
    }

    /**
     * Sets the updated content of the latest version of the source file.
     * @param {String} content Updated content of the source file.
     */
    setUpdatedContent (content) {
        this._activeVersion.setUpdatedContent(content);
    }

    /**
     * Retuns the updated content of the source file.
     * @returns {String} Updated content of the source file.
     */
    getUpdatedContent () {
        return this._activeVersion.getUpdatedContent();
    }

    /**
     * Sets a statement index to the latest version of the source file.
     * @param {JSON} statementIndex Mapping of statements to source file.
     */
    setStatementIndex (statementIndex) {
        this._activeVersion.setStatementIndex(statementIndex);
    }

    /**
     * Returns the statement index for the latest version of the source file.
     * @returns {Object} Statement index of the latest version.
     */
    getStatementIndex () {
        return this._activeVersion.getStatementIndex();
    }

    /**
     * Given a statment ID, return the behavior assigned to the mapped stmt.
     * @param {String} stmtId ID of the mapped statement.
     * @returns {String} ID of the behavior assigned to the mapped statement.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    getMappedStatement (stmtId) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        return stmtIndexEntry;
    }

    /**
     * Returns all the statements with the given behavior ID in the
     * selected version of the source file.
     * @param {String} behaviorId Behavior ID to search for.
     * @returns {Array} List of statements with the given behavior ID.
     */
    getStatementsWithBehavior (behaviorId) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndex = this._activeVersion.getStatementIndex();

        return Object.values(stmtIndex).filter(stmt => stmt.getBehavior() === behaviorId);
    }

    /**
     * For the latest version of the source file, set the behavior ID for
     * the statement with the given statement ID.
     * @param {String} stmtId ID of the mapped statement.
     * @param {String} behaviorId ID of the behavior.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    setBehavior (stmtId, behaviorId) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        stmtIndexEntry.setBehavior(behaviorId);
    }

    /**
     * Clears the behavior ID for the statement with the given stmtId in
     * the latest version of the source file.
     * @param {String} stmtId StmtId of the mapped statement.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    clearBehavior (stmtId) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        stmtIndexEntry.setBehavior(null);
        // TODO: Clear the participants and variables.
    }

    /**
     * Sets participant and variable name for the statement with the stmtId.
     * @param {String} stmtId Statment ID of the mapped statement.
     * @param {String} participantName Name of the participant.
     * @param {String} variableName Name of the variable.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    setParticipant (stmtId, participantName, variableName) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        stmtIndexEntry.setParticipant(participantName, variableName);
    }

    /**
     * Clears the participant with the given participant name from the statement
     * with the given stmtId.
     * @param {String} stmtId Statement ID of the mapped statement.
     * @param {*} participantName Name of the participant to clear.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    removeParticipant (stmtId, participantName) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        stmtIndexEntry.removeParticipantByName(participantName);
    }

    /**
     * Gets particiant with the provided name form the statement with
     * the given statement id.
     * @param {String} stmtId Statement ID of the mapped statement.
     * @param {String} participantName Name of the participant to get.
     * @returns {Object} Participant object with the name and variable.
     * @throws {Error} Throws when active version of source file is not set.
     * @throws {Error} Throws when index does not entry with given stmtId.
     */
    getParticipant (stmtId, participantName) {
        if (!this._activeVersion) {
            throw new Error("No version of source is set as active version.");
        }
        const stmtIndexEntry = this._activeVersion.getStatementByUid(stmtId);
        if (!stmtIndexEntry) {
            throw new Error(`Statement with ID ${stmtId} does not exist in the active version.`);
        }
        return stmtIndexEntry.getParticipantByName(participantName);
    }
};
