export default class StatementIndex {
    constructor () {
        this._index = {};
    }

    // This is from the serialized data when engine is saved.
    loadFromFile (json) {

    }

    // This is from the mapping generated by the parser when
    // a source file is saved.
    loadMap (json) {

    }

    // Given a statement UID, return the entry.
    getEntry (statementId) {
        return this._index[statementId];
    }

    // Get all the entries in this index.
    getEntries () {
        return Object.values(this._index);
    }

    // Given a behavior ID, return the entry that is mapped to it.
    getEntryByBehaviorId (behaviorId) {

    }
};
